# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# config/application.yml

AWS_ACCESS_KEY: "AKIAJE2LJBTCO77OVBPQ"
AWS_SECRET_KEY: "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"
AWS_BUCKET:     "joshuavarghese"
AWS_REGION:     "us-east-1"

SECRET_KEY: sk_live_vR5Nk0w1DH5LZDxH93IVsTZt
PUBLISHABLE_KEY: pk_live_bfuZA9uMiEhA0eIf98WaYVP6